## Cristian Taylor
## 7/19/2024
## DSC320 Math for Data Science 
## Week 6 - Matricies


### Enter the matrices as Numpy arrays

In [20]:
import numpy as np

# Define the matrices A, B, and C
A = np.array([
    [1, -2, 3, 7],
    [2, 1, 1, 4],
    [-3, 2, -2, 10]
])

B = np.array([
    [0, 1, -3,-2],
    [10, -1, 2, -3],
    [5, 1, -1, 4]
])

C = np.array([
    [4, 0, -2, 3],
    [3, 6, 9, 7],
    [2, 2, 5, 1],
    [9, 4, 6, -2]
])


### Determine the dimensions of each matrix

In [21]:
# Get the dimensions of the matrices
dim_A = A.shape
dim_B = B.shape
dim_C = C.shape

(dim_A, dim_B, dim_C)


((3, 4), (3, 4), (4, 4))

### Determine if each matrix operation is defined and calculate the result if defined

 
***𝐴+𝐵***

In [22]:
try:
    A_plus_B = A + B
except ValueError as e:
    A_plus_B = str(e)

A_plus_B


array([[ 1, -1,  0,  5],
       [12,  0,  3,  1],
       [ 2,  3, -3, 14]])

 
***𝐴𝐵***

In [23]:
try:
    AB = np.dot(A, B)
except ValueError as e:
    AB = str(e)

AB


'shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)'

 
***AC***

In [24]:
try:
    AC = np.dot(A, C)
except ValueError as e:
    AC = str(e)

AC


array([[ 67,  22,  37, -22],
       [ 49,  24,  34,   6],
       [ 80,  48,  74, -17]])


 ### Transpose of C

In [25]:
C_T = np.transpose(C)

C_T


array([[ 4,  3,  2,  9],
       [ 0,  6,  2,  4],
       [-2,  9,  5,  6],
       [ 3,  7,  1, -2]])

### Illustrate the property  : Transpose of ***(AC)*** = Transpose of ***C*** * Transpose of ***A***


In [26]:
AC_T = np.transpose(np.dot(A, C))
C_T_A_T = np.dot(np.transpose(C), np.transpose(A))

(AC_T, C_T_A_T)


(array([[ 67,  49,  80],
        [ 22,  24,  48],
        [ 37,  34,  74],
        [-22,   6, -17]]),
 array([[ 67,  49,  80],
        [ 22,  24,  48],
        [ 37,  34,  74],
        [-22,   6, -17]]))

### Inverse of C

In [27]:
try:
    C_inv = np.linalg.inv(C)
except np.linalg.LinAlgError as e:
    C_inv = str(e)

C_inv


array([[ 0.14814815, -0.07407407,  0.14814815,  0.03703704],
       [-0.3       ,  0.35      , -1.05      ,  0.25      ],
       [ 0.02962963, -0.11481481,  0.52962963, -0.09259259],
       [ 0.15555556,  0.02222222,  0.15555556, -0.11111111]])

Import Image - Use Week7_image.jpg

2. Find the resolution of this image. Hint: OpenCV imports the image as a Numpy array, where each
pixel corresponds to an entry in the array.
3. In checking the array dimensions, you should see that three numbers are displayed. What is this third
number, and why is it there?